### ISSUE TITLE
Support for Jessie `import` loader implementation

### ISSUE THREAD

**Issue by michaelfig** [michaelfig/jessica#7]
@smotaal, I understand that you can help add an `import` loader for Jessica.

Such a loader would probably exist in `lib/import.mjs.ts`, with tests under `lang/nodejs/__tests__/import.ts`.  I would expect `lib/import.mjs.ts` to be something like the following, with explicit endowments:

```javascript
fuction makeImport(
  assetLoader: (path: string) => Promise<string>,
  evaluator: (src: string, uri: string) =>Promise<any>): Promise<any>;
export default makeImport;
```

Looking forward to talking more aboot this.

Thanks,
Michael.

**Comment by SMotaal** [comment]
First off, thank you so much for yesterday's amazing walkthrough. It was very informative to understand the moving parts, not just PEG which in my world now evolves from being mysterious to down-right hypnotic 🙂.

I'd like us to get a chance to discuss things in more detail. Maybe hangouts, or I can set up a zoom slot. I think we can put in writing the necessary interfaces once we considered the finer aspects in both domains and outlined the suitable integration paths that would honour grammars, semantics and conformance.

From my side, I'd like to push us to consider `assetLoader` to be a more granular aspect than a univariate and idempotent (ie a single flat map expanding over time) because those to me have been a rather unspoken barrier to ESM adoption in today's pre-realms world, and yet we are working here with notions like attenuation and compartments. I know it's premature to get into specifics, but we should at least make sure we don't end up relying on things that will not translate well moving forward on these fronts.

Should we connect? When? I am open and fairly flexible as long as I am aboot and your are about 🎉

**Comment by michaelfig** [comment]
Just to document this publically, @SMotaal and I discussed the official constraint that Jessie's `import` and `export` statements are only for default imports.  Essentially, Jessica doesn't need an ESM (Ecmascript Standard Modules) implementation, just something that more resembles `require`.

**Comment by michaelfig** [comment]
[importer.mjs.ts](../blob/master/lib/importer.mjs.ts) has a basically working implementation.
